//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.2

pub mod prelude;

pub mod courses;
pub mod families;
pub mod grades;
pub mod parents;
pub mod schools;
pub mod sessions;
pub mod student_course;
pub mod student_current_teacher;
pub mod student_refer_teacher;
pub mod student_session;
pub mod students;
pub mod teachers;
