//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.2

pub use super::courses::Entity as Courses;
pub use super::families::Entity as Families;
pub use super::grades::Entity as Grades;
pub use super::parents::Entity as Parents;
pub use super::schools::Entity as Schools;
pub use super::sessions::Entity as Sessions;
pub use super::student_course::Entity as StudentCourse;
pub use super::student_current_teacher::Entity as StudentCurrentTeacher;
pub use super::student_refer_teacher::Entity as StudentReferTeacher;
pub use super::student_session::Entity as StudentSession;
pub use super::students::Entity as Students;
pub use super::teachers::Entity as Teachers;
