//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sessions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub course_id: Option<u64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub main_teacher_id: Option<u64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::courses::Entity",
        from = "Column::CourseId",
        to = "super::courses::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Courses,
    #[sea_orm(
        belongs_to = "super::teachers::Entity",
        from = "Column::MainTeacherId",
        to = "super::teachers::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Teachers,
}

impl Related<super::courses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Courses.def()
    }
}

impl Related<super::teachers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Teachers.def()
    }
}

impl Related<super::students::Entity> for Entity {
    fn to() -> RelationDef {
        super::student_session::Relation::Students.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::student_session::Relation::Sessions.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
